'use client';
import {useRef,useEffect} from 'react';
import * as THREE from 'three';
import {FragmentEmblem} from './fragment-emblem';
import {journeyProgress} from './journey-timing';
import {WordmarkField} from './wordmark-field';
const clamp=(x:number)=>Math.min(1,Math.max(0,x));
export default function CinematicScene(){const host=useRef<HTMLDivElement>(null);const canvas=useRef<HTMLCanvasElement>(null);
useEffect(()=>{const el=host.current!;const ctx=canvas.current!.getContext('2d')!;let w=innerWidth,h=innerHeight,dpr=1,raf=0,start=performance.now(),last=start;let current=journeyProgress(scrollY/h);let px=-9999,py=-9999,tx=-9999,ty=-9999;let pointerActive=0,activeTarget=0;let renderer:THREE.WebGLRenderer|undefined,scene:THREE.Scene,camera:THREE.OrthographicCamera,modelScene:THREE.Scene,modelCamera:THREE.PerspectiveCamera;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;modelScene=new THREE.Scene();modelCamera=new THREE.PerspectiveCamera(32,w/h,.1,100);modelCamera.position.set(0,0,5.9);
try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0x000000,0);renderer.autoClear=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;el.appendChild(renderer.domElement);scene=new THREE.Scene();camera=new THREE.OrthographicCamera(0,w,0,h,-1000,1000);camera.position.z=100;modelScene.add(new THREE.AmbientLight(0xc5b7ff,1.4));const key=new THREE.DirectionalLight(0xfffaf2,3.5);key.position.set(3,4,4);modelScene.add(key);const rim=new THREE.DirectionalLight(0x9480ff,7);rim.position.set(-4,1,-2);modelScene.add(rim);const fill=new THREE.DirectionalLight(0x887bbb,1.8);fill.position.set(1,-2,3);modelScene.add(fill);
const envScene=new THREE.Scene();envScene.background=new THREE.Color('#1c1830');for(let i=0;i<6;i++){const rect=new THREE.Mesh(new THREE.PlaneGeometry(8,8),new THREE.MeshBasicMaterial({color:[0xf6edff,0x9080dd,0x312444][i%3],side:THREE.DoubleSide}));rect.position.set(Math.cos(i*Math.PI/3)*5,Math.sin(i*Math.PI/3)*5,i%2?4:-4);rect.lookAt(0,0,0);envScene.add(rect)}const gen=new THREE.PMREMGenerator(renderer);const env=gen.fromScene(envScene,.06);modelScene.environment=env.texture;gen.dispose();
}catch{renderer=undefined;}
const emblem=new FragmentEmblem(modelScene,modelCamera);
let field:WordmarkField|undefined,disposed=false,fontsReady=false,lastMetrics=0;
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio,1.75);canvas.current!.width=w*dpr;canvas.current!.height=h*dpr;canvas.current!.style.width=w+'px';canvas.current!.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);if(renderer){renderer.setSize(w,h);camera.left=0;camera.right=w;camera.top=0;camera.bottom=h;camera.updateProjectionMatrix();}modelCamera.aspect=w/h;modelCamera.updateProjectionMatrix();if(fontsReady)field?.resize(w,h,dpr);}
const begin=()=>field?.begin(performance.now());const skip=()=>field?.finish();
addEventListener('velune:entrance-start',begin);addEventListener('velune:entrance-skip',skip);
function render(now:number){const dt=Math.min((now-last)/1000,.04);last=now;const time=(now-start)/1000;const p=journeyProgress(scrollY/h);current+=(p-current)*(1-Math.exp(-dt*11));pointerActive+=(activeTarget-pointerActive)*(1-Math.exp(-dt*8));px+=(tx-px)*(1-Math.exp(-dt*14));py+=(ty-py)*(1-Math.exp(-dt*14));const normalized=clamp(current/3);const phase=Math.min(3,Math.floor(normalized*3.999));document.documentElement.dataset.scene=String(phase);el.style.setProperty('--scene-progress',String(normalized));
const sky=clamp((current-.45)/.65)*(1-clamp((current-1.25)/.55));const final=clamp((current-2.45)/.45);const light=Math.max(sky,final);ctx.clearRect(0,0,w,h);const colorA=[12+light*154,10+light*137,22+light*175];const colorB=[32+light*147,23+light*131,53+light*160];const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,`rgb(${colorA.join(',')})`);grad.addColorStop(.5,`rgb(${colorB.join(',')})`);grad.addColorStop(1,`rgb(${colorA.join(',')})`);ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);const aperture=Math.max(22,h*(.24-clamp(current/.8)*.215));const center=h*(.49+Math.sin(current*.7)*.07);const angle=Math.sin(current*.8)*.18;ctx.save();ctx.translate(w*.5,center);ctx.rotate(angle);const scale=1+Math.sin(current*.6)*.1;
for(let side=-1;side<=1;side+=2){ctx.beginPath();ctx.moveTo(-w*.7,side*h);ctx.lineTo(w*.7,side*h);ctx.lineTo(w*.7,side*(aperture+Math.pow(.7,2)*h*1.4));ctx.bezierCurveTo(w*.3,side*(aperture-h*.05),-w*.3,side*(aperture-h*.05),-w*.7,side*(aperture+Math.pow(.7,2)*h*1.4));ctx.closePath();const wing=ctx.createLinearGradient(0,side*aperture,0,side*h);wing.addColorStop(0,light>.1?'rgba(250,233,255,.75)':'rgba(177,111,244,.40)');wing.addColorStop(.10,'rgba(111,60,180,.16)');wing.addColorStop(.35,light>.1?'rgba(173,150,205,.08)':'rgba(4,2,12,.88)');wing.addColorStop(1,light>.1?'rgba(197,181,224,.10)':'rgba(8,4,17,.92)');ctx.fillStyle=wing;ctx.fill();for(let j=0;j<40;j++){const depth=j/40;ctx.beginPath();for(let x=-w*.7;x<=w*.7;x+=16){const n=x/(w*.7);const arch=n*n*h*.42;const wave=Math.sin(x/w*4+time*.25+depth+current)*h*.005;const y=side*(aperture+arch+depth*depth*h*.65+wave);x===-w*.7?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle=`rgba(${light>.1?'250,220,255':'172,123,226'},${(1-depth)*.15})`;ctx.lineWidth=depth<.1?1.3:.7;ctx.stroke();}}
ctx.restore();const metrics=field?.update(now,dt,{x:px,y:py,active:reduced?0:pointerActive},current,ctx);if(metrics&&now-lastMetrics>160){el.dataset.particleProgress=metrics.progress.toFixed(3);el.dataset.particleCount=String(metrics.count);el.dataset.particleDeviation=metrics.deviation.toFixed(2);el.dataset.particleDelta=dt.toFixed(4);lastMetrics=now;}
const modelMetrics=emblem.update(current,time,w,h,reduced);el.dataset.emblemLoaded=String(modelMetrics.loaded);el.dataset.emblemAssembly=modelMetrics.assembly.toFixed(3);el.dataset.emblemBreakup=modelMetrics.breakup.toFixed(3);el.dataset.emblemFragments=String(modelMetrics.fragments);el.dataset.emblemTriangles=String(modelMetrics.triangles);
if(!renderer){emblem.drawCanvas(ctx,w,h);}else{renderer.clear();renderer.render(scene!,camera!);if(modelMetrics.opacity>.002)renderer.render(modelScene,modelCamera);}
const film=el.querySelector('.scene-film') as HTMLElement;if(film){film.style.opacity=String(.13*(1-light)*clamp(current+.25));film.style.transform=`scale(${1+normalized*.12}) rotate(${normalized*2}deg)`}const journey=document.querySelector('.scroll-journey') as HTMLElement;if(journey){journey.style.setProperty('--journey',String(current));const panels=journey.querySelectorAll<HTMLElement>('.journey-panel');panels.forEach((panel,i)=>{const o=reduced?1:1-clamp((Math.abs(current-i)-.22)/.28);panel.style.opacity=String(o);panel.style.transform=`translate3d(0,${(current-i)*-45}px,0)`;panel.style.visibility=o>.01?'visible':'hidden';panel.style.pointerEvents=o>.5?'auto':'none';panel.setAttribute('aria-hidden',o>.5?'false':'true')});const count=journey.querySelector('.journey-count');if(count)count.textContent='0'+(Math.min(3,Math.round(current))+1)+' / 04';journey.querySelectorAll<HTMLElement>('[data-dot]').forEach((dot,i)=>dot.classList.toggle('active',i===Math.min(3,Math.round(current))))}if(!reduced)raf=requestAnimationFrame(render);}
const move=(e:PointerEvent)=>{tx=e.clientX;ty=e.clientY;activeTarget=1;if(px<-500){px=tx;py=ty}};const leave=()=>{activeTarget=0};const scroll=()=>{if(reduced)render(performance.now())};resize();document.fonts.load("500 32px 'Spline Sans Mono'").catch(()=>[]).then(()=>{if(disposed)return;fontsReady=true;field=new WordmarkField(renderer?scene:undefined,reduced);field.resize(w,h,dpr);el.dataset.particleRenderer=renderer?'webgl':'canvas';const entranceStart=document.documentElement.dataset.veluneEntranceStarted;if(entranceStart)field.begin(Number(entranceStart));else if(!document.documentElement.dataset.veluneEntrance)field.finish();document.documentElement.dataset.veluneSceneReady='true';dispatchEvent(new Event('velune:scene-ready'));if(reduced){field.finish();render(performance.now())}});render(performance.now());addEventListener('resize',resize);addEventListener('pointermove',move);document.addEventListener('pointerleave',leave);addEventListener('scroll',scroll);return()=>{disposed=true;cancelAnimationFrame(raf);removeEventListener('resize',resize);removeEventListener('pointermove',move);document.removeEventListener('pointerleave',leave);removeEventListener('scroll',scroll);field?.dispose();removeEventListener('velune:entrance-start',begin);removeEventListener('velune:entrance-skip',skip);delete document.documentElement.dataset.veluneSceneReady;renderer?.dispose();renderer?.domElement.remove();emblem.dispose();};},[]);
return <div className="cinematic-scene" ref={host} aria-hidden="true"><canvas ref={canvas} className="scene-backdrop"/><video className="scene-film" autoPlay muted loop playsInline preload="metadata" src="/assets/velune-film.mp4"/><div className="scene-grain"/></div>}
