import {majorIds} from '@/lib/major-registry';
import {chainContracts,chainRegistry} from '@/lib/market-registry';
import majors from '@/lib/data/markets.json';
import chainSnapshot from '@/lib/data/chain.json';
const mem=new Map<string,{at:number;value:any}>();
export async function GET(request:Request){const kind=new URL(request.url).searchParams.get('kind')||'majors';if(!['majors','chain'].includes(kind))return Response.json({error:'Invalid market group'},{status:400});const cached=mem.get(kind);if(cached&&Date.now()-cached.at<45000)return Response.json(cached.value,{headers:{'Cache-Control':'public,max-age=30'}});try{let assets:any[]=[];const key=process.env.COINGECKO_API_KEY;const headers:Record<string,string>=key?{'x-cg-demo-api-key':key}:{};
if(kind==='majors'){const r=await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids='+majorIds.join(',')+'&sparkline=true&per_page=100',{headers,signal:AbortSignal.timeout(7000)});if(!r.ok)throw Error();const d:any=await r.json();if(!Array.isArray(d)||!d.length)throw Error();assets=d.map((x:any)=>({id:x.id,symbol:x.symbol.toUpperCase(),name:x.name,price:x.current_price,change:x.price_change_percentage_24h||0,volume:x.total_volume,marketCap:x.market_cap,high:x.high_24h,low:x.low_24h,image:x.image,points:x.sparkline_in_7d?.price||[],category:'majors',updated:x.last_updated}));}
else{const batches=[];for(let i=0;i<chainContracts.length;i+=30)batches.push(chainContracts.slice(i,i+30));const responses=await Promise.all(batches.map(async batch=>{const r=await fetch('https://api.dexscreener.com/tokens/v1/robinhood/'+batch.join(','),{signal:AbortSignal.timeout(7000)});if(!r.ok)throw Error();const rows:any=await r.json();if(!Array.isArray(rows))throw Error();return rows}));const d=responses.flat();const groups=new Map(chainRegistry.map(x=>[x.address.toLowerCase(),x.group]));const seen=new Set();assets=d.filter((p:any)=>p.chainId==='robinhood'&&groups.has(p.baseToken?.address?.toLowerCase())&&Number(p.priceUsd)>0).sort((a:any,b:any)=>(b.liquidity?.usd||0)-(a.liquidity?.usd||0)).filter((p:any)=>!seen.has(p.baseToken.address)&&seen.add(p.baseToken.address)).map((p:any)=>({id:p.baseToken.address,address:p.baseToken.address,pool:p.pairAddress,symbol:p.baseToken.symbol,name:p.baseToken.name,price:Number(p.priceUsd),change:p.priceChange?.h24||0,volume:p.volume?.h24||0,marketCap:p.marketCap||p.fdv,liquidity:p.liquidity?.usd||0,image:p.info?.imageUrl,points:[],category:'chain',group:groups.get(p.baseToken.address.toLowerCase()),url:p.url,venue:p.dexId,pair:p.baseToken.symbol+' / '+p.quoteToken.symbol}));if(!assets.length)throw Error();}
const result={assets,source:kind==='majors'?'CoinGecko':'DexScreener',updated:kind==='majors'?assets.map(a=>a.updated).sort().at(-1):new Date().toISOString(),cached:false};mem.set(kind,{at:Date.now(),value:result});return Response.json(result,{headers:{'Cache-Control':'public,max-age=30'}});
}catch{return Response.json({...kind==='majors'?majors:chainSnapshot,cached:true},{headers:{'Cache-Control':'public,max-age=15'}})}}
